// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendation.proto

package distributed.recommendation;

public final class RecommendationProto {
  private RecommendationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024recommendation.proto\022\016recommendation\032\014" +
      "common.proto2\217\001\n\016Recommendation\022B\n\025reque" +
      "stRecommendation\022\022.common.RequestDTO\032\023.c" +
      "ommon.ResponseDTO\"\000\0229\n\014pollDatabase\022\022.co" +
      "mmon.RequestDTO\032\023.common.ResponseDTO\"\000B8" +
      "\n\037at.mkaran.thesis.recommendationB\023Recom" +
      "mendationProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          at.mkaran.thesis.common.CommonProto.getDescriptor(),
        }, assigner);
    at.mkaran.thesis.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
